# 07/10/2020

## Numpy and Inbuilt Functions

In [1]:
import numpy as np

In [2]:
#Creating Arrays

my_list =[1,2,3,4,5,6,7,8]
my_list1 =[1,2,3,4,5,6,7,8]
arr=np.array([my_list, my_list1]) #one dimensional array

In [3]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [4]:
arr=arr.reshape(4,4)

In [5]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr[:2,:2]

array([[1, 2],
       [5, 6]])

In [8]:
arr[1:3,1:3]

array([[6, 7],
       [2, 3]])

In [9]:
arr[2:,2:]

array([[3, 4],
       [7, 8]])

In [10]:
arrr=np.arange(1,20,step=2)
arrr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [12]:
#Broadcasting and Copy function 

arrr[3:]=100
arrr

array([  1,   3,   5, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arrr1=arrr


In [14]:
arrr1[3:]=500
arrr1

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

In [15]:
arrr

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

In [16]:
arrr2=arrr.copy()
print('arrr=',arrr)
arrr2[3:]=10
arrr2

arrr= [  1   3   5 500 500 500 500 500 500 500]


array([ 1,  3,  5, 10, 10, 10, 10, 10, 10, 10])

In [17]:
# Some Useful Conditions for Exploratory Data Analysis

new=np.arange(0,30,3)

In [18]:
new>10

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [19]:
new/3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
print (new)

new[new>=15]

[ 0  3  6  9 12 15 18 21 24 27]


array([15, 18, 21, 24, 27])

In [25]:
np.arange(0,20,1).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
arrr*arrr2

array([   1,    9,   25, 5000, 5000, 5000, 5000, 5000, 5000, 5000])

In [28]:
np.ones(10,dtype=int).reshape(2,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.random.rand(3,6)

array([[0.7597248 , 0.61003913, 0.50933745, 0.64606858, 0.13381132,
        0.55689881],
       [0.48444164, 0.39016493, 0.77837938, 0.9625611 , 0.23917578,
        0.90711608],
       [0.8268345 , 0.91703518, 0.82574221, 0.53358748, 0.97176375,
        0.34604922]])

In [33]:
np.random.randn()

-1.6807738774459453

In [40]:
np.random.randint(0,5)

4